- alloc_funds: &id001 !!python/object/apply:quant.engine.consts.ShowTypes
  - !!python/tuple [20]
  desc: "\u6D77\u9F9F\u7B56\u7565"
  job_id: '1'
  name: "\u6D77\u9F9F\u7B56\u7565"
  pick_symbols:
    market: !!python/object/apply:quant.engine.consts.ShowTypes
    - !!python/tuple [80]
    type: &id002 !!python/object/apply:quant.engine.consts.ShowTypes
    - !!python/tuple [30]
    universe: [AAPL, AMZN]
  pick_time: {flat: 'cross_down(close,rolling_min(low,20))', long: 'cross_up(close,rolling_max(high,20))'}
- alloc_funds: *id001
  desc: "\u5747\u7EBF\u7A81\u7834"
  job_id: '2'
  name: "\u5747\u7EBF\u7A81\u7834"
  pick_symbols:
    market: !!python/object/apply:quant.engine.consts.ShowTypes
    - !!python/tuple [82]
    type: *id002
    universe: [AAPL, AMZN]
  pick_time: {flat: 'cross_down(close,ma(close,20))', long: 'cross_up(close,ma(close,10))'}
